# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\siras\Documents\maya\scripts\maya_devToolsManager\ui\devTools_manager.ui'
#
# Created: Tue Feb 20 02:40:00 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DebHub_ui(object):
    def setupUi(self, DebHub_ui):
        DebHub_ui.setObjectName("DebHub_ui")
        DebHub_ui.resize(537, 439)
        self.centralwidget = QtGui.QWidget(DebHub_ui)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setMargin(0)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_tools = QtGui.QWidget()
        self.tab_tools.setObjectName("tab_tools")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_tools)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_tool = QtGui.QListWidget(self.tab_tools)
        self.listWidget_tool.setObjectName("listWidget_tool")
        self.verticalLayout_3.addWidget(self.listWidget_tool)
        self.tabWidget.addTab(self.tab_tools, "")
        self.tab_setting = QtGui.QWidget()
        self.tab_setting.setObjectName("tab_setting")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_setting)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_setting_global = QtGui.QGroupBox(self.tab_setting)
        self.groupBox_setting_global.setObjectName("groupBox_setting_global")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_setting_global)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtGui.QLineEdit(self.groupBox_setting_global)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_Location = QtGui.QLabel(self.groupBox_setting_global)
        self.label_Location.setObjectName("label_Location")
        self.gridLayout.addWidget(self.label_Location, 0, 0, 1, 1)
        self.pushButton_location_openExplorer = QtGui.QPushButton(self.groupBox_setting_global)
        self.pushButton_location_openExplorer.setObjectName("pushButton_location_openExplorer")
        self.gridLayout.addWidget(self.pushButton_location_openExplorer, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_setting_global)
        self.setting_main_verticalLayout = QtGui.QVBoxLayout()
        self.setting_main_verticalLayout.setObjectName("setting_main_verticalLayout")
        self.label_2 = QtGui.QLabel(self.tab_setting)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.setting_main_verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.setting_main_verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.tab_setting)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_setting, "")
        self.verticalLayout.addWidget(self.tabWidget)
        DebHub_ui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DebHub_ui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuUtils = QtGui.QMenu(self.menubar)
        self.menuUtils.setObjectName("menuUtils")
        DebHub_ui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DebHub_ui)
        self.statusbar.setObjectName("statusbar")
        DebHub_ui.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuUtils.menuAction())

        self.retranslateUi(DebHub_ui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DebHub_ui)

    def retranslateUi(self, DebHub_ui):
        DebHub_ui.setWindowTitle(QtGui.QApplication.translate("DebHub_ui", "Dev Hub", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DebHub_ui", "Tool develop", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tools), QtGui.QApplication.translate("DebHub_ui", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_setting_global.setTitle(QtGui.QApplication.translate("DebHub_ui", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Location.setText(QtGui.QApplication.translate("DebHub_ui", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_location_openExplorer.setText(QtGui.QApplication.translate("DebHub_ui", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DebHub_ui", "- Empty -", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("DebHub_ui", "save setting", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setting), QtGui.QApplication.translate("DebHub_ui", "Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DebHub_ui", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuUtils.setTitle(QtGui.QApplication.translate("DebHub_ui", "Utility", None, QtGui.QApplication.UnicodeUTF8))

